name: Publish

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18.18.0

            - name: Install dependencies
              run: yarn install

            - name: Build
              run: |
                  npm run lint
                  npm run test

            - name: Ci
              run: npm ci

            - name: Publish
              if: startsWith(github.head_ref, 'release-auto-v')
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  npm run pub
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish-next
              if: startsWith(github.head_ref, 'release-auto-next-v')
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  npm run pub-next
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
